name: tcc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.3.3
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - isort=4.3.21
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - mccabe=0.6.1
  - ncurses=6.2
  - openssl=1.1.1f
  - pip=20.0.2
  - pylint=2.4.4
  - python=3.8.1
  - readline=7.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlalchemy=1.3.13
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - cffi==1.14.0
    - chardet==3.0.4
    - idna==2.9
    - pycparser==2.19
    - python-dotenv==0.12.0
    - requests==2.23.0
    - urllib3==1.25.8

